"""Add business details fields to OnboardingRequest

Revision ID: a52b9ec095dc
Revises: 
Create Date: 2025-01-31 18:15:49.898357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52b9ec095dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('business_type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('business_address', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_request', schema=None) as batch_op:
        batch_op.drop_column('business_address')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('business_type')
        batch_op.drop_column('business_name')

    # ### end Alembic commands ###
